import { createHash, randomUUID } from 'node:crypto';
import type { Response } from 'express';
import { EmailStatus } from '@prisma/client';
import { z } from 'zod';
import { prisma } from '../config/prisma.js'; import { env } from '../config/env.js';
import { emailQueue } from '../queues/email.queue.js'; import { indexEmail, searchEmails } from '../services/search.service.js'; import { availableSenders } from '../services/mailer.service.js';
import type { AuthenticatedRequest } from '../middleware/auth.js';
const scheduleSchema=z.object({sender:z.string().email(),subject:z.string().min(1).max(500),body:z.string().min(1),recipients:z.array(z.string().email()).min(1).max(10000),scheduledAt:z.string().datetime(),campaignId:z.string().optional(),minDelaySeconds:z.coerce.number().min(0).max(3600).default(2),hourlyLimit:z.coerce.number().int().positive().max(100000).optional()});
async function getUser(req:AuthenticatedRequest){const auth=req.auth!;return prisma.user.upsert({where:{email:auth.email},update:{name:auth.name,image:auth.image},create:{email:auth.email,name:auth.name,image:auth.image}})}
const jobId=(userId:string,recipient:string,at:string,campaign:string)=>createHash('sha256').update(`${userId}:${recipient}:${at}:${campaign}`).digest('hex');
export async function scheduleEmails(req:AuthenticatedRequest,res:Response){const input=scheduleSchema.parse(req.body),user=await getUser(req),when=new Date(input.scheduledAt),campaign=input.campaignId||randomUUID(),minDelayMs=Math.max(env.MIN_SEND_DELAY_MS,input.minDelaySeconds*1000);if(!availableSenders().includes(input.sender))return res.status(400).json({error:'Select a configured SMTP sender'});const records=[];for(const recipient of [...new Set(input.recipients.map(x=>x.toLowerCase()))]){const id=jobId(user.id,recipient,when.toISOString(),campaign);const email=await prisma.email.upsert({where:{jobId:id},update:{},create:{jobId:id,campaignId:campaign,userId:user.id,sender:input.sender,recipient,subject:input.subject,body:input.body,scheduledAt:when,status:EmailStatus.SCHEDULED,minDelayMs,hourlyLimit:input.hourlyLimit}});await emailQueue.add('deliver-email',{emailId:email.id,userId:user.id,sender:email.sender,recipient,subject:email.subject,body:email.body,scheduledAt:when.toISOString(),minDelayMs:email.minDelayMs,hourlyLimit:email.hourlyLimit??undefined},{jobId:id,delay:Math.max(0,when.getTime()-Date.now()),attempts:3,backoff:{type:'exponential',delay:5000},removeOnComplete:1000,removeOnFail:5000});await indexEmail(email);records.push(email)}res.status(201).json({campaignId:campaign,scheduled:records.length,emails:records})}
export async function listEmails(req:AuthenticatedRequest,res:Response){const user=await getUser(req),status=req.query.status as EmailStatus|undefined;res.json(await prisma.email.findMany({where:{userId:user.id,...(status?{status}:{})},orderBy:{scheduledAt:'desc'},take:200}))}
export async function search(req:AuthenticatedRequest,res:Response){const user=await getUser(req),page=Math.max(1,Number(req.query.page)||1),results=await searchEmails(String(req.query.q||''),req.query.status as string|undefined,page);res.json({...results,items:results.items.filter((item:any)=>item.userId===user.id)})}
export async function me(req:AuthenticatedRequest,res:Response){const user=await getUser(req);res.json({email:user.email,name:user.name,image:user.image,slackConnected:Boolean(user.slackWebhookUrl)})}
export function senders(_:AuthenticatedRequest,res:Response){res.json(availableSenders())}
